In [1]:
# library dependencies
import numpy as np
from pathlib import Path
import matplotlib.pyplot as plt
import lzma
import pickle
from sklearn.model_selection import train_test_split
import keras
from keras import layers
import tensorflow as tf
import keras_tuner
import math

2024-01-18 22:01:38.959739: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-01-18 22:01:38.961056: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-01-18 22:01:38.978652: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-01-18 22:01:38.978668: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-01-18 22:01:38.979169: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to

In [2]:
# method to store data as serialized binary structure lzma compressed
def can_pickles(data, filename):
    with lzma.LZMAFile(filename, 'wb') as f:
        pickle.dump(data, f, pickle.DEFAULT_PROTOCOL)

# method to retrieve data from a compressed pickle file (created with the method above)
def uncan_pickles(filename):
    with lzma.LZMAFile(filename, 'rb') as f:
        return pickle.load(f)

In [3]:
# read the prepared data
X = uncan_pickles('../data/onehot_x_lung.pickle.xz')
y = uncan_pickles('../data/onehot_y_lung.pickle.xz')

In [4]:
# build an inhomogenous numpy array from the training set
X = np.array(X, dtype=object)

In [5]:
# convert type of target values from string to float
y = np.array(y).astype(float)

In [6]:
len(X), len(y)

(8201, 8201)

### Rewrite to only use TF Dataset

In [7]:
# shuffle data before building a dataset
# helps to make sure that the input data is shuffled without getting knots in the brain due to lazy execution
rng = np.random.default_rng(1202)
rand_idx = np.arange(len(X))
rng.shuffle(rand_idx)

In [8]:
# show that the list of integers is randomized
rand_idx

array([4301, 1552, 6386, ..., 3572, 5989, 6785])

In [9]:
# now sort the X and y train arrays according to the sorted indicds
X = X[rand_idx]
y = y[rand_idx]

In [10]:
%%time
# create the ragged tensor from the feature array
X = tf.ragged.constant(X, dtype=tf.int8, ragged_rank=1, row_splits_dtype=tf.int32)

CPU times: user 15min 52s, sys: 2min 47s, total: 18min 40s
Wall time: 18min 41s


In [ ]:
# the following creates datasets from feature and label array
# this is an alternative version to create the full dataset
# X_ds = tf.data.Dataset.from_tensor_slices(X)
# y_ds = tf.data.Dataset.from_tensor_slices(y)

In [11]:
# from the TF documentation
full_dataset = tf.data.Dataset.from_tensor_slices((X, y))

# this version where each component is a dataset anlready that is then joined works too
# full_dataset = tf.data.Dataset.zip((X_ds, y_ds))

# this was suggested on the TF forum for this problem
# but does not work because the ragged tensor doesn't have a len
# full_dataset = tf.data.Dataset.from_tensor_slices([X, y])

In [12]:
# take a look at what the dataset elements look like
full_dataset.element_spec

(RaggedTensorSpec(TensorShape([None, 4]), tf.int8, 0, tf.int32),
 TensorSpec(shape=(), dtype=tf.float64, name=None))

In [13]:
# padded batches from ragged tensors are not supported (yet)
# it needs a work around creating a uniform tensor
# idea from : https://github.com/tensorflow/tensorflow/issues/39163
def reformat(data, label):
    return data, label

In [14]:
# apply the transformation
full_dataset = full_dataset.map(reformat)

In [15]:
# now look again - the ragged tensor is gone in this version
full_dataset.element_spec

(TensorSpec(shape=(None, 4), dtype=tf.int8, name=None),
 TensorSpec(shape=(), dtype=tf.float64, name=None))

In [20]:
# check the content of the dataset again
count = 0
for f, l in full_dataset:
    print(f)
    print(l)
    count += 1
    if count == 5: break

tf.Tensor(
[[1 0 0 0]
 [0 0 1 0]
 [1 0 0 0]
 ...
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]], shape=(3882, 4), dtype=int8)
tf.Tensor(4.195, shape=(), dtype=float64)
tf.Tensor(
[[1 0 0 0]
 [0 0 1 0]
 [0 1 0 0]
 ...
 [0 1 0 0]
 [0 1 0 0]
 [1 0 0 0]], shape=(537, 4), dtype=int8)
tf.Tensor(5.272, shape=(), dtype=float64)
tf.Tensor(
[[0 0 1 0]
 [0 0 0 1]
 [0 0 0 1]
 ...
 [0 1 0 0]
 [1 0 0 0]
 [1 0 0 0]], shape=(1764, 4), dtype=int8)
tf.Tensor(5.73, shape=(), dtype=float64)
tf.Tensor(
[[0 0 1 0]
 [0 0 0 1]
 [1 0 0 0]
 ...
 [0 0 1 0]
 [0 1 0 0]
 [0 0 1 0]], shape=(6298, 4), dtype=int8)
tf.Tensor(4.298, shape=(), dtype=float64)
tf.Tensor(
[[1 0 0 0]
 [0 0 0 1]
 [0 0 0 1]
 ...
 [1 0 0 0]
 [0 1 0 0]
 [0 0 0 1]], shape=(3394, 4), dtype=int8)
tf.Tensor(4.069, shape=(), dtype=float64)


In [17]:
# split the full dataset in two sub sets
train_all_dataset = full_dataset.take(math.ceil(len(full_dataset) * 0.8))
test_dataset = full_dataset.skip(math.ceil(len(full_dataset) * 0.8))

In [21]:
# verify the length of the datasets
l_full = len(full_dataset)
l_train = len(train_all_dataset)
l_test = len(test_dataset)
l_full, l_train, l_test, l_train + l_test

(8201, 6561, 1640, 8201)

In [22]:
# size of each batch
batch_size = 64

In [ ]:
# the following two cells are _ONLY_ for TEST and VALIDATION split

In [ ]:
# for one shot training sort before apply padding
train_dataset = train_all_dataset.take(math.ceil(len(train_all_dataset) * 0.8))
val_dataset = train_all_dataset.skip(math.ceil(len(train_all_dataset) * 0.8))

In [ ]:
train_dataset = sorted(train_dataset, key=lambda x: len(x[0]))
train_dataset = train_dataset.padded_batch(batch_size)

In [ ]:
# model setup

In [23]:
def test_model():
    inputs = layers.Input(shape=(None, 4))
    conv1 = layers.Conv1D(
        filters=32,
        kernel_size=10,
        strides=1,
        activation='relu',
        padding='valid'
    )(inputs)
    norm1 = layers.BatchNormalization()(conv1)
    drop1 = layers.Dropout(
        rate=0.1
    )(norm1)
    pool1 = layers.GlobalMaxPool1D()(drop1)
    dense = layers.Dense(16, activation='relu')(pool1)
    outputs = layers.Dense(1)(dense)
    
    # model
    model = keras.Model(inputs=inputs, outputs=outputs, name='Test')
    
    return model

In [24]:
def run_model(model, tds, vds, epochs=100):
    model.summary()
    
    model.compile(
        loss=keras.losses.MeanSquaredError(),
        optimizer=keras.optimizers.Adam(),
        metrics=keras.metrics.MeanAbsoluteError()
    )
    
    history = model.fit(
        tds,
        epochs=epochs,
        validation_data=vds,
        verbose=0
    )
    
    val_mse, val_mae = model.evalute(test_dataset)

    return val_mae

In [ ]:
type(train_all_dataset)

In [ ]:
foo = train_all_dataset.padded_batch(batch_size)
foo

In [ ]:
num_splits = 5

In [ ]:
train_all_dataset.window(math.ceil(len(train_all_dataset) / num_splits))

In [27]:
conc_ds = None
for w in train_all_dataset.window(math.ceil(len(train_all_dataset) / num_splits)):
    print(w)
    print(w[0].element_spec)
    print(type(w))
    tmp = tf.data.Dataset.zip(w)
    print(type(tmp))
    if conc_ds == None:
        conc_ds = tmp
    else:
        conc_ds.concatenate(tmp)
        
conc_ds = conc_ds.padded_batch(batch_size)

(<_VariantDataset element_spec=TensorSpec(shape=(None, 4), dtype=tf.int8, name=None)>, <_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.float64, name=None)>)
TensorSpec(shape=(None, 4), dtype=tf.int8, name=None)
<class 'tuple'>
<class 'tensorflow.python.data.ops.zip_op._ZipDataset'>
(<_VariantDataset element_spec=TensorSpec(shape=(None, 4), dtype=tf.int8, name=None)>, <_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.float64, name=None)>)
TensorSpec(shape=(None, 4), dtype=tf.int8, name=None)
<class 'tuple'>
<class 'tensorflow.python.data.ops.zip_op._ZipDataset'>
(<_VariantDataset element_spec=TensorSpec(shape=(None, 4), dtype=tf.int8, name=None)>, <_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.float64, name=None)>)
TensorSpec(shape=(None, 4), dtype=tf.int8, name=None)
<class 'tuple'>
<class 'tensorflow.python.data.ops.zip_op._ZipDataset'>
(<_VariantDataset element_spec=TensorSpec(shape=(None, 4), dtype=tf.int8, name=None)>, <_VariantDataset element_spe

In [30]:
# for cross validation split train

# list of scores of each fold
all_scores = []
# number of splits to perform
num_splits = 5
# size of each batch
batch_size = 64

# create the split datasets
splits = train_all_dataset.window(math.ceil(len(train_all_dataset) / num_splits))

print('k-fold cross validation with', num_splits, 'splits')

# loop over the splits
for i in range(num_splits):
    print('  split:', i)

    # initialize the training and validation dataset
    val_ds = None
    train_ds = None

    # loop over all dataset splits
    for l, p in enumerate(splits):
        # create a temporary dataset from the tuple returned
        # weird, probably ugly way to do this but for some reason the window operation
        # does not return a valid dataset but a tuple of datasets
        tmp_ds = tf.data.Dataset.zip(p)
        
        # use the DS with the same id as the current split run as validation set
        if l == i:
            val_ds = tmp_ds
        # use everything else for training
        elif train_ds == None:
            train_ds = tmp_ds
        else:
            train_ds.concatenate(tmp_ds)

    print(type(val_ds))
    print(type(train_ds))
    
    for argh in train_ds:
        print(argh)
        break

    # train_ds = sorted(train_ds, key=lambda x: len(x[0]))
    train_ds = train_ds.padded_batch(batch_size)

    score = 0
    # score = run_model(test_model, train_ds, val_ds)
    print('  score:', score)
    
    all_scores.append(score)

# calculate score
mean_score = np.mean(all_scores)
print('mean score:', mean_score)

# rerun training with train_all_dataset
# train_all_dataset = sorted(train_all_dataset, key=lambda x: len(x[0]))
# train_all_dataset = train_all_dataset.padded_batch(batch_size)
# run training
# score = run_model(danq_model, train_all_dataset, test_dataset)

k-fold cross validation with 5 splits
  split: 0
<class 'tensorflow.python.data.ops.zip_op._ZipDataset'>
<class 'tensorflow.python.data.ops.zip_op._ZipDataset'>
(<tf.Tensor: shape=(2987, 4), dtype=int8, numpy=
array([[0, 0, 1, 0],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       ...,
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int8)>, <tf.Tensor: shape=(), dtype=float64, numpy=5.135>)
  score: 0
  split: 1
<class 'tensorflow.python.data.ops.zip_op._ZipDataset'>
<class 'tensorflow.python.data.ops.zip_op._ZipDataset'>
(<tf.Tensor: shape=(3882, 4), dtype=int8, numpy=
array([[1, 0, 0, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       ...,
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0]], dtype=int8)>, <tf.Tensor: shape=(), dtype=float64, numpy=4.195>)
  score: 0
  split: 2
<class 'tensorflow.python.data.ops.zip_op._ZipDataset'>
<class 'tensorflow.python.data.ops.zip_op._ZipDataset'>
(<tf.Tensor: shape=(3882, 4), dtype=int8, numpy=
array([[1, 0, 0,

2024-01-18 22:48:46.459483: W tensorflow/core/framework/dataset.cc:959] Input of Window will not be optimized because the dataset does not implement the AsGraphDefInternal() method needed to apply optimizations.


In [ ]:
dataset = tf.data.Dataset.range(7).window(3)
print(dataset.element_spec)
for window in dataset:
    print(window)
    print(window.element_spec)

### Data Preparation

Split data in train and test subsets and then split the train subset again in train and validation.

A simple verification if the X and y correlation are preserved on the split is done.

In [ ]:
# split in train and test sub sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1202)

In [ ]:
# pad test input (variable input is not accepted)
# X_test = tf.keras.preprocessing.sequence.pad_sequences(X_test, padding="post")

In [ ]:
# split the train set again in train and validation
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=1202)

In [ ]:
# find the first unique PTR value that is also in y_train
train_idx = 0
for i in range(len(y)):
    count = 0
    for l in range(len(y)):
        if i != l and y[i] == y[l]:
            count += 1
            continue
    if count == 0:
        for m in range(len(y_train)):
            if y[i] == y_train[m]:
                train_idx = m
                break
train_idx

In [ ]:
# get a sample
X_train[train_idx]

In [ ]:
# get the matching target
search_y = y_train[train_idx]
search_y

In [ ]:
# find the target value in the raw dataset
full_idx = 0
for i in range(len(y)):
    if y[i] == search_y:
        print(i)
        full_idx = i

In [ ]:
# compare if the raw dataset entry matches the subset entry
if X[full_idx].all() == X_train[train_idx].all():
    print('OK')

### Sort Training Data

In [ ]:
# build an inhomogenous numpy array from the training set
X_train = np.array(X_train, dtype=object)

In [ ]:
# build an array containing the sequence lengths
sequence_lengths = list(map(lambda x: len(x), X_train))

In [ ]:
# sort the array but only get the indices
sorted_indices = np.argsort(sequence_lengths)

In [ ]:
sorted_indices

In [ ]:
# now sort the X and y train arrays according to the sorted indicds
X_train = X_train[sorted_indices]
y_train = y_train[sorted_indices]

In [ ]:
# check if the previously found values still correlate
for i in range(len(y_train)):
    if y_train[i] == search_y:
        print(X_train[i])

### Ragged Tensor Tests

In [ ]:
# this does not work since the sequences are of different length
# X_test_dataset = tf.data.Dataset.from_tensor_slices((X_test, y_test))

In [ ]:
X_train_tensor = tf.ragged.constant(X_train, dtype=tf.int8, ragged_rank=1, row_splits_dtype=tf.int32)
X_val_tensor = tf.ragged.constant(X_val, dtype=tf.int8, ragged_rank=1, row_splits_dtype=tf.int32)

In [ ]:
X_train_dataset = tf.data.Dataset.from_tensor_slices((X_train_tensor, y_train))
X_val_dataset = tf.data.Dataset.from_tensor_slices((X_val_tensor, y_val))

In [ ]:
X_train_dataset.element_spec

In [ ]:
X_val_dataset.element_spec

In [ ]:
# padded batches from ragged tensors are not supported (yet)
# it needs a work around creating a uniform tensor
# idea from : https://github.com/tensorflow/tensorflow/issues/39163
def reformat(data, label):
    return data, label

In [ ]:
X_train_dataset = X_train_dataset.map(reformat)
X_val_dataset = X_val_dataset.map(reformat)

In [ ]:
bar = sorted(X_train_dataset, key=lambda x: len(x[0]))

In [ ]:
bar = X_val_dataset.as_numpy_iterator()

In [ ]:
count = 0
for x, y in bar:
    print(y)
    if count == 5:
        break    
    count += 1

In [ ]:
moo, boo = zip(*bar)

In [ ]:
foo = tf.ragged.constant(moo, dtype=tf.int8, ragged_rank=1, row_splits_dtype=tf.int32)

In [ ]:
len(X_val_dataset)

In [ ]:
size = math.ceil(len(X_val_dataset) * 0.3)
size

In [ ]:
foo = X_val_dataset.window(size)

In [ ]:
for w in foo:
    print(w)
    print(len(w[0]))

In [ ]:
for i, s in enumerate(foo):
    print(i, s)
    s.concatenate(foo)

In [ ]:
# shuffle the dataset (again) and create padded batches
batch_size = 32
X_train_dataset = X_train_dataset.shuffle(buffer_size=len(X_train), seed=1202).padded_batch(batch_size)
X_val_dataset = X_val_dataset.shuffle(buffer_size=len(X_val), seed=1202).padded_batch(batch_size)

In [ ]:
# optinally repeat the dataset multiple times -> WHY?
# rep = 3
# X_train_dataset = X_train_dataset.repeat(rep)
# X_val_dataset = X_val_dataset.repeat(rep)

In [ ]:
datalen = []
ds_iterator = iter(X_train_dataset)
for data, label in ds_iterator:
    datalen.append(len(data[1]))

In [ ]:
datalen[:5]

In [ ]:
# testing if keras can use the dataset
model = tf.keras.Sequential([
    tf.keras.layers.Dense(16, activation='relu', input_shape=(None,4)),
    tf.keras.layers.Dense(1, activation='sigmoid')
])
model.compile(optimizer='adam', loss='mse', metrics=['mae'])
model.fit(X_train_dataset, epochs=1)